[workspace]
members = [ "data-redis-example",
    "fetching-data-example",
    "files-examples",
    "func-examples",
    "generic-examples",
    "hof-examples",
    "iterator-examples",
    "macros-examples",
    "scraping-example",
]
